require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MessageDatasourcesController do

  # This should return the minimal set of attributes required to create a valid
  # MessageDatasource. As you add validations to MessageDatasource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MessageDatasourcesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all message_datasources as @message_datasources" do
      message_datasource = MessageDatasource.create! valid_attributes
      get :index, {}, valid_session
      assigns(:message_datasources).should eq([message_datasource])
    end
  end

  describe "GET show" do
    it "assigns the requested message_datasource as @message_datasource" do
      message_datasource = MessageDatasource.create! valid_attributes
      get :show, {:id => message_datasource.to_param}, valid_session
      assigns(:message_datasource).should eq(message_datasource)
    end
  end

  describe "GET new" do
    it "assigns a new message_datasource as @message_datasource" do
      get :new, {}, valid_session
      assigns(:message_datasource).should be_a_new(MessageDatasource)
    end
  end

  describe "GET edit" do
    it "assigns the requested message_datasource as @message_datasource" do
      message_datasource = MessageDatasource.create! valid_attributes
      get :edit, {:id => message_datasource.to_param}, valid_session
      assigns(:message_datasource).should eq(message_datasource)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MessageDatasource" do
        expect {
          post :create, {:message_datasource => valid_attributes}, valid_session
        }.to change(MessageDatasource, :count).by(1)
      end

      it "assigns a newly created message_datasource as @message_datasource" do
        post :create, {:message_datasource => valid_attributes}, valid_session
        assigns(:message_datasource).should be_a(MessageDatasource)
        assigns(:message_datasource).should be_persisted
      end

      it "redirects to the created message_datasource" do
        post :create, {:message_datasource => valid_attributes}, valid_session
        response.should redirect_to(MessageDatasource.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved message_datasource as @message_datasource" do
        # Trigger the behavior that occurs when invalid params are submitted
        MessageDatasource.any_instance.stub(:save).and_return(false)
        post :create, {:message_datasource => { "name" => "invalid value" }}, valid_session
        assigns(:message_datasource).should be_a_new(MessageDatasource)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MessageDatasource.any_instance.stub(:save).and_return(false)
        post :create, {:message_datasource => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested message_datasource" do
        message_datasource = MessageDatasource.create! valid_attributes
        # Assuming there are no other message_datasources in the database, this
        # specifies that the MessageDatasource created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MessageDatasource.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => message_datasource.to_param, :message_datasource => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested message_datasource as @message_datasource" do
        message_datasource = MessageDatasource.create! valid_attributes
        put :update, {:id => message_datasource.to_param, :message_datasource => valid_attributes}, valid_session
        assigns(:message_datasource).should eq(message_datasource)
      end

      it "redirects to the message_datasource" do
        message_datasource = MessageDatasource.create! valid_attributes
        put :update, {:id => message_datasource.to_param, :message_datasource => valid_attributes}, valid_session
        response.should redirect_to(message_datasource)
      end
    end

    describe "with invalid params" do
      it "assigns the message_datasource as @message_datasource" do
        message_datasource = MessageDatasource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MessageDatasource.any_instance.stub(:save).and_return(false)
        put :update, {:id => message_datasource.to_param, :message_datasource => { "name" => "invalid value" }}, valid_session
        assigns(:message_datasource).should eq(message_datasource)
      end

      it "re-renders the 'edit' template" do
        message_datasource = MessageDatasource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MessageDatasource.any_instance.stub(:save).and_return(false)
        put :update, {:id => message_datasource.to_param, :message_datasource => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested message_datasource" do
      message_datasource = MessageDatasource.create! valid_attributes
      expect {
        delete :destroy, {:id => message_datasource.to_param}, valid_session
      }.to change(MessageDatasource, :count).by(-1)
    end

    it "redirects to the message_datasources list" do
      message_datasource = MessageDatasource.create! valid_attributes
      delete :destroy, {:id => message_datasource.to_param}, valid_session
      response.should redirect_to(message_datasources_url)
    end
  end

end
