require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TemplateStrategiesController do

  # This should return the minimal set of attributes required to create a valid
  # TemplateStrategy. As you add validations to TemplateStrategy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "message_config" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TemplateStrategiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all template_strategies as @template_strategies" do
      template_strategy = TemplateStrategy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:template_strategies).should eq([template_strategy])
    end
  end

  describe "GET show" do
    it "assigns the requested template_strategy as @template_strategy" do
      template_strategy = TemplateStrategy.create! valid_attributes
      get :show, {:id => template_strategy.to_param}, valid_session
      assigns(:template_strategy).should eq(template_strategy)
    end
  end

  describe "GET new" do
    it "assigns a new template_strategy as @template_strategy" do
      get :new, {}, valid_session
      assigns(:template_strategy).should be_a_new(TemplateStrategy)
    end
  end

  describe "GET edit" do
    it "assigns the requested template_strategy as @template_strategy" do
      template_strategy = TemplateStrategy.create! valid_attributes
      get :edit, {:id => template_strategy.to_param}, valid_session
      assigns(:template_strategy).should eq(template_strategy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TemplateStrategy" do
        expect {
          post :create, {:template_strategy => valid_attributes}, valid_session
        }.to change(TemplateStrategy, :count).by(1)
      end

      it "assigns a newly created template_strategy as @template_strategy" do
        post :create, {:template_strategy => valid_attributes}, valid_session
        assigns(:template_strategy).should be_a(TemplateStrategy)
        assigns(:template_strategy).should be_persisted
      end

      it "redirects to the created template_strategy" do
        post :create, {:template_strategy => valid_attributes}, valid_session
        response.should redirect_to(TemplateStrategy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved template_strategy as @template_strategy" do
        # Trigger the behavior that occurs when invalid params are submitted
        TemplateStrategy.any_instance.stub(:save).and_return(false)
        post :create, {:template_strategy => { "message_config" => "invalid value" }}, valid_session
        assigns(:template_strategy).should be_a_new(TemplateStrategy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TemplateStrategy.any_instance.stub(:save).and_return(false)
        post :create, {:template_strategy => { "message_config" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested template_strategy" do
        template_strategy = TemplateStrategy.create! valid_attributes
        # Assuming there are no other template_strategies in the database, this
        # specifies that the TemplateStrategy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TemplateStrategy.any_instance.should_receive(:update).with({ "message_config" => "" })
        put :update, {:id => template_strategy.to_param, :template_strategy => { "message_config" => "" }}, valid_session
      end

      it "assigns the requested template_strategy as @template_strategy" do
        template_strategy = TemplateStrategy.create! valid_attributes
        put :update, {:id => template_strategy.to_param, :template_strategy => valid_attributes}, valid_session
        assigns(:template_strategy).should eq(template_strategy)
      end

      it "redirects to the template_strategy" do
        template_strategy = TemplateStrategy.create! valid_attributes
        put :update, {:id => template_strategy.to_param, :template_strategy => valid_attributes}, valid_session
        response.should redirect_to(template_strategy)
      end
    end

    describe "with invalid params" do
      it "assigns the template_strategy as @template_strategy" do
        template_strategy = TemplateStrategy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TemplateStrategy.any_instance.stub(:save).and_return(false)
        put :update, {:id => template_strategy.to_param, :template_strategy => { "message_config" => "invalid value" }}, valid_session
        assigns(:template_strategy).should eq(template_strategy)
      end

      it "re-renders the 'edit' template" do
        template_strategy = TemplateStrategy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TemplateStrategy.any_instance.stub(:save).and_return(false)
        put :update, {:id => template_strategy.to_param, :template_strategy => { "message_config" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested template_strategy" do
      template_strategy = TemplateStrategy.create! valid_attributes
      expect {
        delete :destroy, {:id => template_strategy.to_param}, valid_session
      }.to change(TemplateStrategy, :count).by(-1)
    end

    it "redirects to the template_strategies list" do
      template_strategy = TemplateStrategy.create! valid_attributes
      delete :destroy, {:id => template_strategy.to_param}, valid_session
      response.should redirect_to(template_strategies_url)
    end
  end

end
